uploads = []

[[generated]]
id = "r65dIFBVQXO9XVxQ4iSh-"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SaHOOg_nEE2fZFbbwP7hw"
uri = "file://artifacts/mobile/assets/images/splash-bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KJ3Vz8_i2TXcf_FpBigs5"
uri = "file://artifacts/mobile/assets/images/glow-orb.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "hOGx6G9SToy1eU_463lO1"
uri = "file://backend_implementation.md"
type = "text"
title = "Nervana — Backend Implementation Bible"

[[outputs]]
id = "FO733otVvTqkvOtlYndJ2"
uri = "file://README.md"
type = "text"
title = "README.md — Developer Onboarding Guide"

[[outputs]]
id = "h2ENNBeylFqORSFaOBiH_"
uri = "file://tech_debt.md"
type = "text"
title = "tech_debt.md — Master Engineering Checklist"

[[outputs]]
id = "umQh8fDp4ypCQ6XiKxYjF"
uri = "file://frontend_repointing.md"
type = "text"
title = "frontend_repointing.md — API Integration Guide"
